# Generated by Django 4.0.6 on 2022-07-14 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Porject',
            new_name='Project',
        ),
    ]
